export const IMAGES = {
  image1: require('../assets/images/image1.png'),
  top_image: require('../assets/images/top_image.png'),
  but1: require('../assets/images/but1.png'),
  but2: require('../assets/images/bun2.png'),
  fb: require('../assets/images/fb.png'),
  google: require('../assets/images/google.png'),
  logo: require('../assets/images/logo.png'),
  search: require('../assets/images/search.png'),
  bell: require('../assets/images/bell.png'),
  cover: require('../assets/images/cover.png'),
  all: require('../assets/images/all.png'),
  all2: require('../assets/images/all2.png'),
  all3: require('../assets/images/all3.png'),
  all4: require('../assets/images/all4.png'),
  all5: require('../assets/images/all5.png'),
  all6: require('../assets/images/all6.png'),
  slide1: require('../assets/images/slide1.png'),
  slide2: require('../assets/images/slide2.png'),
  slide3: require('../assets/images/slide3.png'),
  flat1: require('../assets/images/flat1.png'),
  flat2: require('../assets/images/flat2.png'),
  flat3: require('../assets/images/flat3.png'),
  flat4: require('../assets/images/flat4.png'),
  fas1: require('../assets/images/fas1.png'),
  fas2: require('../assets/images/fas2.png'),
  fas3: require('../assets/images/fas3.png'),
  fas4: require('../assets/images/fas4.png'),
  fas5: require('../assets/images/fas5.png'),
  fas6: require('../assets/images/fas6.png'),
  wid1: require('../assets/images/wid1.png'),
  wid2: require('../assets/images/wid2.png'),
  wid3: require('../assets/images/wid3.png'),
  wid4: require('../assets/images/wid4.png'),
  group2: require('../assets/images/Group2.png'),
  pro1: require('../assets/images/pro1.png'),
  pro2: require('../assets/images/pro2.png'),
  pro3: require('../assets/images/pro3.png'),
  pro4: require('../assets/images/pro4.png'),
  pro5: require('../assets/images/pro5.png'),
  pro6: require('../assets/images/pro6.png'),
  pro7: require('../assets/images/pro7.png'),
  pro8: require('../assets/images/pro8.png'),
};

export const ICONS = {
  white_logo: require('../assets/icons/white_logo.png'),
  logo_black: require('../assets/icons/logo_black.png'),
};

export const FONTS = {
  Poppins_100I: 'Poppins-ThinItalic',
  Poppins_100: 'Poppins-Thin',
  Poppins_600I: 'Poppins-SemiBoldItalic',
  Poppins_600: 'Poppins-SemiBold',
  Poppins_400: 'Poppins-Regular',
  Poppins_500I: 'Poppins-MediumItalic',
  Poppins_500: 'Poppins-Medium',
  Poppins_300I: 'Poppins-LightItalic',
  Poppins_300: 'Poppins-Light',
  Poppins_400I: 'Poppins-Italic',
  Poppins_200I: 'Poppins-ExtraLightItalic',
  Poppins_200: 'Poppins-ExtraLight',
  Poppins_800I: 'Poppins-ExtraBoldItalic',
  Poppins_800: 'Poppins-ExtraBold',
  Poppins_700I: 'Poppins-BoldItalic',
  Poppins_700: 'Poppins-Bold',
};
export const COLORS = {
  white: '#ffffff',
  gradient2: '#D4DEFD',
  gradient1: '#D8CAFF',
  black: '#000000',
  dark_gradient: '#213369',
  card: '#E1E1FA',
  light_text_color: '#5B6C97',
  dark_text_color: '#ffffff',
};
